import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, posix } from "node:path";

const root = process.cwd();
const distDir = process.env.NEXT_DIST_DIR || ".next";
const staticRoot = join(root, distDir, "static");
const publicRoot = join(root, "public");

const PUBLIC_SHELL_ASSETS = [
  "/manifest.webmanifest",
  "/icon-32x32.png",
  "/icon-192x192.png",
  "/icon-512x512.png",
  "/apple-touch-icon.png",
  "/app-icon.png",
];

function walkFiles(dir, urlPrefix) {
  const urls = [];

  if (!existsSync(dir)) return urls;

  for (const name of readdirSync(dir)) {
    const fullPath = join(dir, name);
    const urlPath = posix.join(urlPrefix, name);

    if (statSync(fullPath).isDirectory()) {
      urls.push(...walkFiles(fullPath, urlPath));
      continue;
    }

    urls.push(urlPath);
  }

  return urls;
}

function collectPrecacheUrls() {
  const urls = new Set(PUBLIC_SHELL_ASSETS);

  // Do not precache /_next/static — stale hashed bundles were masking UI updates via caches.match().
  // Icons and the web manifest are enough for the installable shell.

  for (const name of readdirSync(publicRoot)) {
    if (name === "sw.js" || name.startsWith("Old")) continue;

    const fullPath = join(publicRoot, name);
    if (!statSync(fullPath).isFile()) continue;

    const lower = name.toLowerCase();
    if (
      lower.endsWith(".png") ||
      lower.endsWith(".svg") ||
      lower.endsWith(".ico") ||
      lower.endsWith(".webp") ||
      lower.endsWith(".woff") ||
      lower.endsWith(".woff2")
    ) {
      urls.add(`/${name}`);
    }
  }

  return [...urls].sort();
}

function buildCacheVersion(urls) {
  return createHash("sha256").update(urls.join("\n")).digest("hex").slice(0, 12);
}

function renderServiceWorker(precacheUrls, cacheVersion) {
  return `/* Generated by scripts/generate-sw.mjs — do not edit by hand. */
const CACHE_VERSION = ${JSON.stringify(cacheVersion)};
const PRECACHE_CACHE = ${JSON.stringify(`cultosol-precache-${cacheVersion}`)};
const RUNTIME_CACHE = ${JSON.stringify(`cultosol-runtime-${cacheVersion}`)};
const PRECACHE_URLS = ${JSON.stringify(precacheUrls, null, 2)};

const OFFLINE_HTML = \`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="theme-color" content="#059669" />
  <title>CULTOSOL — Offline</title>
  <style>
    body {
      margin: 0;
      min-height: 100vh;
      display: grid;
      place-items: center;
      padding: 1.5rem;
      font-family: system-ui, -apple-system, Segoe UI, sans-serif;
      background: #f4fff8;
      color: #0f172a;
    }
    main {
      max-width: 22rem;
      text-align: center;
    }
    h1 {
      margin: 0 0 0.5rem;
      font-size: 1.25rem;
    }
    p {
      margin: 0;
      line-height: 1.5;
      color: rgb(15 23 42 / 0.72);
    }
  </style>
</head>
<body>
  <main>
    <h1>CULTOSOL</h1>
    <p>You are offline. Open CULTOSOL once while online so it can finish installing for offline use.</p>
  </main>
</body>
</html>\`;

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(PRECACHE_CACHE);
      await Promise.all(
        PRECACHE_URLS.map(async (url) => {
          try {
            await cache.add(new Request(url, { cache: "reload" }));
          } catch {
            /* Some optional assets may be missing in certain builds. */
          }
        })
      );
      await self.skipWaiting();
    })()
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      // Drop every previous CULTOSOL cache (including unversioned cultosol-runtime).
      await Promise.all(
        keys
          .filter((key) => key.startsWith("cultosol-") && key !== PRECACHE_CACHE && key !== RUNTIME_CACHE)
          .map((key) => caches.delete(key))
      );
      await self.clients.claim();
    })()
  );
});

function isSameOrigin(request) {
  try {
    return new URL(request.url).origin === self.location.origin;
  } catch {
    return false;
  }
}

function isApiRequest(url) {
  return url.pathname.startsWith("/api/");
}

function isStaticAsset(url) {
  // Never cacheFirst /_next/* — hashed or not, stale app shells were masking UI updates.
  return (
    url.pathname === "/manifest.webmanifest" ||
    /\\.(png|svg|ico|webp|woff2?)$/i.test(url.pathname)
  );
}

function isDocumentRequest(request) {
  return (
    request.mode === "navigate" ||
    (request.headers.get("accept") || "").includes("text/html")
  );
}

async function cacheFirst(request) {
  const cached = await caches.match(request);
  if (cached) return cached;

  const response = await fetch(request);
  if (response.ok) {
    const cache = await caches.open(RUNTIME_CACHE);
    await cache.put(request, response.clone());
  }
  return response;
}

async function networkFirstDocument(request) {
  const runtimeCache = await caches.open(RUNTIME_CACHE);

  try {
    const response = await fetch(request);
    if (response.ok) {
      await runtimeCache.put(request, response.clone());
    }
    return response;
  } catch {
    const cached =
      (await caches.match(request)) ||
      (await caches.match("/")) ||
      (await caches.match("/index.html"));

    if (cached) return cached;

    return new Response(OFFLINE_HTML, {
      status: 200,
      headers: { "Content-Type": "text/html; charset=utf-8" },
    });
  }
}

async function networkFirstRuntime(request) {
  const runtimeCache = await caches.open(RUNTIME_CACHE);

  try {
    const response = await fetch(request);
    if (response.ok) {
      await runtimeCache.put(request, response.clone());
    }
    return response;
  } catch {
    const cached = await caches.match(request);
    if (cached) return cached;
    throw new Error("Network unavailable");
  }
}

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET" || !isSameOrigin(request)) return;

  const url = new URL(request.url);
  // Let the network handle API + Next bundles; SW must not serve stale app JS.
  if (isApiRequest(url) || url.pathname.startsWith("/_next/")) return;

  if (isStaticAsset(url)) {
    event.respondWith(cacheFirst(request));
    return;
  }

  if (isDocumentRequest(request)) {
    event.respondWith(networkFirstDocument(request));
    return;
  }

  event.respondWith(
    networkFirstRuntime(request).catch(() => caches.match(request))
  );
});

self.addEventListener("message", (event) => {
  if (event.data === "SKIP_WAITING") {
    void self.skipWaiting();
  }
});
`;
}

function main() {
  const precacheUrls = collectPrecacheUrls();
  const cacheVersion =
    precacheUrls.length > 0 ? buildCacheVersion(precacheUrls) : "dev-runtime";
  const outputPath = join(publicRoot, "sw.js");

  writeFileSync(outputPath, renderServiceWorker(precacheUrls, cacheVersion), "utf8");

  console.log(
    `Generated ${outputPath} with ${precacheUrls.length} precache URL(s), version ${cacheVersion}.`
  );
}

main();
