-- User-named range plantillas (sets) with optional CIC overrides.
-- Member rows live in user_custom_ranges.range_set_id.

create table if not exists public.user_custom_range_sets (
  range_set_id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  sample_type text not null,
  crop_id bigint null references public.crops (crop_id) on delete set null,
  cic_overrides jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  is_deleted boolean not null default false,
  deleted_at timestamptz null,
  constraint user_custom_range_sets_sample_type_check
    check (sample_type in ('soil', 'foliar', 'water')),
  constraint user_custom_range_sets_name_not_blank
    check (char_length(trim(name)) > 0)
);

create index if not exists user_custom_range_sets_user_sample_idx
  on public.user_custom_range_sets (user_id, sample_type)
  where is_deleted = false;

alter table public.user_custom_ranges
  add column if not exists range_set_id bigint null
    references public.user_custom_range_sets (range_set_id) on delete set null;

create index if not exists user_custom_ranges_range_set_idx
  on public.user_custom_ranges (range_set_id)
  where range_set_id is not null and coalesce(is_deleted, false) = false;

alter table public.user_custom_range_sets enable row level security;

drop policy if exists "Users can read own custom range sets" on public.user_custom_range_sets;
create policy "Users can read own custom range sets"
  on public.user_custom_range_sets
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own custom range sets" on public.user_custom_range_sets;
create policy "Users can insert own custom range sets"
  on public.user_custom_range_sets
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own custom range sets" on public.user_custom_range_sets;
create policy "Users can update own custom range sets"
  on public.user_custom_range_sets
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own custom range sets" on public.user_custom_range_sets;
create policy "Users can delete own custom range sets"
  on public.user_custom_range_sets
  for delete
  using (auth.uid() = user_id);

grant select, insert, update, delete on public.user_custom_range_sets to authenticated;
grant usage, select on sequence public.user_custom_range_sets_range_set_id_seq to authenticated;
